name: deep-mri-placenta-gaussian-stochastic-reconstruction

debug:
  True

slice_index: 9

mc_samples: 5

dataset:
  name: placenta
#  num_workers: 0 # default 0 because we do not use large batch size with 3D model and volumes anyways
  data_dir: '/home/moucheng/projects_data/placenta'

model:
  name: mlp
  nparams: 2 # dim of the output of the encoder, meaning number of components of the encoded signals
  samples: 2
  mri: t2adc
#  width: 8

train:
  lr: 0.001
  epochs_no: 200
  stop_epoch: 1000
  batch_size: 128
  patience: 5
  alpha: 0.0002
  anneal_rate: 0.00001
  warm_up: 0.2

checkpoint:
  resume: False
  checkpoint_path: '/some/path/to/saved/model'

logger:
  tag: 'debug'

seed: 1024




