name: deep-mri-project-vae-stochastic-reconstruction

debug:
  True

slice_index: 70

mc_samples: 2

dataset:
  name: simulated
  data_dir: '/home/moucheng/projects_data/HCP/103818_1'

save_path: '/home/moucheng/projects/2023_03_09b_MICCAI_mri'

model:
  name: gaussian
  samples: 3 # latent variable dimension
  nparams: 2 # dim of the output of the encoder, meaning number of components of the encoded signals
  mri: msdki
  act: 'relu'
  prior_std: 0.01

train:
  lr: 0.001
  epochs_no: 400
  batch_size: 128
  alpha: 0.001
  anneal_rate: 0.0005
  warm_up: 0.2

checkpoint:
  resume: False
  checkpoint_path: '/some/path/to/saved/model'

logger:
  tag: 'debug'

seed: 1024




