name: deep-mri-project-baseline-l2-deterministic-reconstruction

debug:
  True

slice_index: 70

mc_samples: 2

save_path: '/home/moucheng/projects/2023_03_09_MICCAI/baselines/self supervised/models_hpc/mlp/mlp_par_5_mri_ball_stick_lr_0.001_epoch_200'

model_full_path: 'mlp_par_5_mri_ball_stick_lr_0.001_epoch_200.pt'

dataset:
  name: hpc
#  num_workers: 0 # default 0 because we do not use large batch size with 3D model and volumes anyways
  data_dir: '/home/moucheng/projects_data/HCP/103818_1'

model:
  name: gaussian
  nparams: 5 # dim of the output of the encoder, meaning number of components of the encoded signals
  mri: ball_stick

train:
  lr: 0.001
  epochs_no: 200
  stop_epoch: 200
  batch_size: 128
  patience: 5

checkpoint:
  resume: False
  checkpoint_path: '/some/path/to/saved/model'

logger:
  tag: 'debug'

seed: 1024




